name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    uses: Omer-hadad-s-Projects/workflows/.github/workflows/docker-image-builder.yaml@master 
    with:
      image_name: thetemani/wakeonlanapi
      default_branch: master                    
      changelog_path: CHANGELOG.md             
      docker_context: .                       
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}